[Details]
Name = "Caster's Compendium"
ID = "io.github.hybriduofa.casterdeckbuilder"
Version = "0.1.3"
Build = 1
Icon = "../../data/images/shadow.png"

[Migrations]
fyneDo = true

[LinuxAndBSD]
GenericName = "Card Deck Builder"
Categories = ["Game"]
Comment = "Build Caster Chronicles decks and export them for Tabletop Simulator"
Keywords = ["cards", "deck", "deckbuilder", "tabletop"]
